title: Architekkt
description: Dependency Graph Visualizer for Your iOS and macOS App. Feel the magical satisfaction of a simple and clean software architecture.
url: "/JekyllArchitekkt"

# Build settings
theme: minima
permalink: "/:title"

# Production variables
cuttly_count: "https://cutt.ly/architekkt"
cuttly_download_count: "https://cutt.ly/architekktlatest"
