title: Architekkt
description: Dependency Graph Visualizer for Your iOS and macOS App. Feel the magical satisfaction of a simple and clean software architecture.
url: "/JekyllArchitekkt"

# Build settings
theme: minima

