- title: One Step Solution
  description: Choose your project and you're ready to go. No mental overhead.
  image: assets/images/service_step.png
- title: Clean Interface
  description: Experience an understandable and intuitive interface.
  image: assets/images/service_interface.png
- title: Complete AST
  description: Browse the fully resolved AST. Everthing is covered.
  image: assets/images/service_ast.png
- title: Force-directed Graph
  description: Let physics do the work and gain an eye for the essentials .
  image: assets/images/service_graph.png
- title: No Tracking
  description: Architekkt does not track you. Just write us if something bothers you.
  image: assets/images/service_tracking.png
- title: Full Pipeline
  description: There is more to come to build the best software architecture tool.
  image: assets/images/service_pipeline.png